// <auto-generated />
using CompanyTaskManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyTaskManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828103049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyTaskManagement.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ameobatronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vigo Solutions"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Auxin.io"
                        });
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arun"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Karthik"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ravi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kumar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Suresh"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mano"
                        });
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.TaskCompany", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("TaskCompanies");
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.TaskEmployee", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TaskEmployees");
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.TaskCompany", b =>
                {
                    b.HasOne("CompanyTaskManagement.Models.Company", "Company")
                        .WithMany("TaskCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyTaskManagement.Models.TaskItem", "Task")
                        .WithMany("TaskCompanies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.TaskEmployee", b =>
                {
                    b.HasOne("CompanyTaskManagement.Models.Employee", "Employee")
                        .WithMany("TaskEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyTaskManagement.Models.TaskItem", "Task")
                        .WithMany("TaskEmployees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.Company", b =>
                {
                    b.Navigation("TaskCompanies");
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.Employee", b =>
                {
                    b.Navigation("TaskEmployees");
                });

            modelBuilder.Entity("CompanyTaskManagement.Models.TaskItem", b =>
                {
                    b.Navigation("TaskCompanies");

                    b.Navigation("TaskEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
